# Naziv tijeka rada koji će se prikazivati u "Actions" tabu na GitHubu
name: Deploy to GitHub Pages

# Okidači (triggers) - pokreni ovaj tijek rada na push na 'main' granu
on:
  push:
    branches:
      - main
  # Omogućuje i ručno pokretanje iz Actions taba
  workflow_dispatch:

# Postavljanje dozvola za GITHUB_TOKEN kako bi se omogućilo postavljanje na Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Definicija poslova (jobs)
jobs:
  # Posao za izgradnju (build) aplikacije
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Verzija iz vašeg pnpm-lock.yaml

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Koristite verziju Node.js koja odgovara vašem projektu
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build # Ova naredba će sada generirati 'out' direktorij

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Direktorij sa statičkim datotekama

  # Posao za postavljanje (deploy) izgrađenog artefakta
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4